### ISSUE TITLE
Add keyboard command to Ctrl+P command Palette

### ISSUE THREAD

**Issue by AdrianSimionov** [Heziode/obsidian-antidote#1]
Add option to Ctrl+P command palette with a function similar to clicking the spellcheck button. Allow the plugin settings to configure a keyboard shortcut for the newly added command.

This will allow users to open Antidote spellcheck from keyboard instead of using a mouse action.

**Comment by Heziode** [comment]
very good idea!

@Samuel-Martineau, do you want to do it?
