### ISSUE TITLE
Unable to communicate with Connectix Agent(Antidote)

### ISSUE THREAD

**Issue by YIRU69** [Heziode/obsidian-antidote#12]
I am new to use this plugin. Firstly I really appreciate for you.
When I use it, it debug "Unable to communicate with Connectix Agent(Antidote)".
Could you help me?

**Comment by Heziode** [comment]
Hi,

Which operating system did you use, and what version of Antidote and Connectix are you using?

**Comment by YIRU69** [comment]
On windows. 
I have never use antidote but I look the officially website.

**Comment by YIRU69** [comment]
It meanning I must have a accout on antidote. Right?

**Comment by Heziode** [comment]
Yes, Antidote is a paid corrector, you need to [purchase a license](https://www.antidote.info/en/store/first-purchase) in order to use Antidote.

When you have you licence, you can install Antidote and Connectix, the agent which links Antidote and integrations (Word, VS Code, Obsidian, etc.)

**Comment by YIRU69** [comment]
Thank you, I know what I should do.

**Comment by Freymat** [comment]
Hi. Thank you for this great plugin !
I'm using Antidote (I purchased a license) on windows, and connectix works with all my softwares ( word, VScode, firefox, etc.)
But with your plugin in Obsidian, I get the error :Unable to communicate with Connectix Agent (Antidote).

How can I solve this issue, please ?

**Comment by Heziode** [comment]
Hi @Freymat,

Can you please, give me the following information:

- Windows version
- Obsidian plugin version
- Antidote version
- Connectix version

**Comment by Freymat** [comment]
Hi @Heziode,
i'm using:
- win 11
- obsidian 1.3.5
- antidote 10.6.1557
- connectix 10.6.1557
Thank you !

**Comment by Freymat** [comment]
Hi @Heziode,
would you please have any idea why the plugin can't communicate with Connectix ?

Best regards,
Freymat

**Comment by Heziode** [comment]
Hi @Freymat, sorry for the delay.

This plugin only works with Connectix version 11.

As said in the README (plugin page):

> In order to use Antidote 10 (or web) with this plugin, you will have to install the latest version of Connectix (version 11 or higher). Connectix is the bridge between Obsidian and Antidote (10, 11+, web), so by keeping Antidote 10 with Connectix 11, you will be able to use this plugin.

So, by installing Connectix version 11, and keeping Antidote 10 (or upgrading to version 11 if you can) you will be able to use this plugin.

**Comment by Freymat** [comment]
Hi @Heziode . Thank you for your answer. Do you know if there is a way to install Connectix 11 and run it with Antidote 10 ?

**Comment by Heziode** [comment]
You can download Connectix 11 from your [Client Portal](https://services.druide.com/client/), under the "Useful links" section: "Connectix Utility for Antidote Web"

**Comment by Freymat** [comment]
Thanks a lot @Heziode !
Have a nice day,
Freymat

**Comment by Freymat** [comment]
Hi, I finally installed connectix 11 on a "brand new" Ubuntu (Zorin OS 16.3 based on Ubuntu 20.04 LTS). I mean a new install from scratch.

Connectix 11.3.447
Antidote 10 v6.3 (paid)
Obsidian 1.3.7 

Antidote is working.
Connectors with Firefox, Vscode, etc. are working.

But when I try to use the plugin, I get the error message "Impossible de communiquer avec l'agent connectix (Antidote)"

Would you have any idea, directions to investigate in order to figure out what's going wrong ?

I thank you !

**Comment by Heziode** [comment]
Hi @Freymat,

I tested on your configuration (Zorin OS 16.3 core, and with the same version for Connectix, Antidote and Obsidian):

![Capture from ZorinOS 16.3](https://github.com/Heziode/obsidian-antidote/assets/16735076/c8563b8c-0df8-4552-a6a7-f8514490f555)

And it works in my side. I use the latest version of the plugin (2.1.2).
I do not see where s the problem on your config

**Comment by Freymat** [comment]
Thank you for your test 🙏
I tried to remove the plugin and add it again without success.

![Capture d’écran de 2023-08-11 18-00-53](https://github.com/Heziode/obsidian-antidote/assets/77881783/1daa4f07-6543-4089-a9b9-1b91f86b96f4)



Le ven. 11 août 2023 à 13:29, Quentin Dauprat ***@***.***> a
écrit :

**Comment by Heziode** [comment]
Did you have firewall rules enabled on localhost/127.0.0.1?

The plugin try to communicate to the Connectix Agent with `wss://127.0.0.1:PORT` with port something like 55026.

Is this command return something?

```bash
/usr/local/bin/AgentConnectixConsole --api
```

Otherwise what is the return of the followings commands?

```bash
# Check if Connectix agent is running
ps aux | grep AgentAnti

# Check on which port the agent is listening
lsof -i -P | grep AgentAnti
```

**Comment by Freymat** [comment]
Hi Heziode. Sorry I was away for some days.

`/usr/local/bin/AgentConnectixConsole --api` returns `{"port":55636}me@my_computer:~$`

```
me@my_computer:~$ ps aux | grep AgentAnti
me    3819  0.0  0.0  19268  3224 ?        S    07:46   0:00 /bin/bash /usr/local/bin/AgentAntidote
me    3826  0.0  6.3 2344524 1025960 ?     Sl   07:46   0:03 /opt/Druide/Antidote10/Application/Bin/AgentAntidote.bin
me   20608  0.0  0.0  18828  2484 pts/1    S+   09:42   0:00 grep --color=auto AgentAnti
```

```
me@my_computer:~$ lsof -i -P | grep AgentAnti
AgentAnti 3819 me   22u  IPv4  51567      0t0  TCP localhost:55636 (LISTEN)
AgentAnti 3819 me   23u  IPv4  52153      0t0  TCP localhost:55636->localhost:34514 (ESTABLISHED)
AgentAnti 3826 me   22u  IPv4  51567      0t0  TCP localhost:55636 (LISTEN)
AgentAnti 3826 me   23u  IPv4  52153      0t0  TCP localhost:55636->localhost:34514 (ESTABLISHED)
```
