### ISSUE TITLE
Does not work with the new version of Obsidian

### ISSUE THREAD

**Issue by nj376** [Heziode/obsidian-antidote#13]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Fantastic plug-in. I'm using the 2.1.1 version on Mac (macOS Monterey Version 12.6.1), and unfortunately since the new version of Obsidian (1.3.0 - Installer 1.2.8), it does not work anymore. 

Antidote version : Antidote bilingue v4.0.1 (Français 11.4.5767 | Anglais 11.4.5767)
macOS version : Monterey Version 12.6.1
Obsidian version : 1.3.0 - Installer 1.2.8
Plugin version : 2.1.1

**Comment by Heziode** [comment]
Hi,

I cannot reproduce it.
It works great on my side with:

Antidote version: Français 11.3.5077 | Anglais 11.3.5077 with Connectix version Version 11.4.0.1 (1104.59.27)
macOS: Ventura 13.3.1
Obsidian version: 1.2.8 (Installer 0.15.9)
Plugin version: 2.1.1

The only differences I see are the OS version (which is higher in my case), and the Antidote version, where you French and English version are higher than me, and I do not find anywhere how to get the 11.4. The website and Connectix updater only allows me to get the latest 11.3.

**Comment by nj376** [comment]
Bonjour Quentin,

Everything had been working fine for weeks. The reported problem happened immediately after the last Obsidian update.

My computer:

iMac (Retina 5K, 27-inch, 2020)
Processor 3.6 GHz Intel Core i9 10 cores
Memory 128 GB 2667 MHz DDR4

- I deleted all other plugins → no change
- I reinstalled Obsidian → no change

Strange thing, I don't have this problem with the Macbook Pro (which is under Ventura) with the same obsidian configuration!

For the moment I'm doing the corrections with the Macbook, waiting to understand why it doesn't work anymore on the iMac

**Comment by Heziode** [comment]
I do not have a Monterey to test. But it seems more a Connectix issue with "older" mac version than an issue of this plugin.

**Comment by cdahmedeh** [comment]
I'm having the same issue on Windows 11, clicking any of the corrector or dictionary buttons on the toolbar don't do anything. It works fine in other applications like Microsoft Word and Mozilla Firefox

What I tried:
- Reinstalled Antidote and Connectix
- Restart my PC
- Delete and reinstall the plugin, both manually and through the community browser plugin in 
- Removing all other plugins
- Creating a new notebook

Razer Blade 16 (13th Gen Intel(R) Core(TM) i9-13950HX, 64 GB RAM, 3 TB SSD, RTX 4080)
Microsoft Windows 11 Pro Version	10.0.22621 Build 22621
Antidote English 11.3.4470
Antidote French 11.3.4470
Connectix 11.3.447
Plugin 2.1.1

**Comment by nj376** [comment]
I think it's the new version of Antidote that's the problem, because having updated Antidote on the Macbook Pro, now it doesn't work on this machine either :(

**Comment by Heziode** [comment]
Hum… maybe we should contact the support of Antidote.

Does @Acibi or @alaroucheDruide have some insights about this issue?

**Comment by nj376** [comment]
For the moment the only "solution" I found is to use the new Antidote 11 clipboard correction feature:

- I copy all the text on the Obsidian page ( CMD+C )
- I use the Antidote clipboard correction function ( OPT+CMD+K )
- I make the corrections
- I paste the corrected text on the Obsidian page ( CM+V )

**Comment by nj376** [comment]
> I do not have a Monterey to test. But it seems more a Connectix issue with "older" mac version than an issue of this plugin.

I've just tried it with a new-generation Mac, freshly installed with the latest version of Obsidian and Antidote, and ... same problem.

**Comment by Heziode** [comment]
I also have this issue with the latest version of Obsidian.

I will investigate.

**Comment by Heziode** [comment]
Okey, it is fixed in https://github.com/Heziode/obsidian-antidote/releases/tag/2.1.2

Sorry for the delay

**Comment by cdahmedeh** [comment]
Thanks @Heziode 

I can confirm that it works now on my system. Cheers!
