### ISSUE TITLE
Not working anymore with Obsidian 1.6.5 on MacOS

### ISSUE THREAD

**Issue by tcrouzet** [Heziode/obsidian-antidote#16]
Error message : Unable to communicate with Connectix Agent…

Tested on a new vault with this plugin alone…

plugin:antidote-gram…cker-integration:38 Error: socket hang up
    at Socket.socketOnEnd (node:_http_client:524:23)
    at Socket.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
﻿

**Comment by Heziode** [comment]
Hello,

Can you give me the following information:

- Antidote version
- Connectix version
- macOS version

**Comment by tcrouzet** [comment]
Sorry, after reboot, everything OK… I 'm using Sonoma 14.2.1, Antidote 11 V6 and Connectix 11.6.

PS : merci pour le plugin, indispensable, faut que je publie les miens…

**Comment by Heziode** [comment]
Thanks for the feedback!

---

C'est un bon exercice de publier des extensions (ou du code de manière générale) surtout en open-source :)
