### ISSUE TITLE
Inconsistent results for Fountain syntax

### ISSUE THREAD

**Issue by AdrianSimionov** [Heziode/obsidian-antidote#6]
I have a .md file which is written in fountain syntax, please see below:
https://github.com/Darakah/obsidian-fountain

The script is a bit over 3600 characters.

When clicking the button to start Antidote for correction, the results are very inconsistent, depending of where I click in the fountain script, I can anything from a few words to several lines of text in Antidote. Never the whole text.

**Comment by Heziode** [comment]
I do not see any inconsistency. It is the same behavior with the official VS Code extension, and official Microsoft Word integration.

The part of the text that is sent to Antidote, depends on the cursor location.

If you place the cursor at the beginning of the document, it will try to load the whole document.
The plugin sends to Antidote the text from the current cursor (or the beginning of the line where the cursor is) to the end of the document, or only send the selection to Antidote.

From my point of view, there are no problems here.

Maybe @Acibi have some remark about this?

**Comment by AdrianSimionov** [comment]
Thanks for clarification, unfortunately I was not aware of this undocumented feature and my clicks and selections were random into the document, with the expectation that always, the whole document will be sent to Antidote.

**Comment by AdrianSimionov** [comment]
Would it be possible to add a toggle setting, disabled by default, which when enabled will send the whole block of text to Antidote instead of only the text from cursor onward (with the exception of selected text functionality which remains the same)?

**Comment by alaroucheDruide** [comment]
Alex here, from Druide.
We’re working on documenting the interaction between documents and Antidote. @Heziode is right though for the initial spec: the position of the cursor will decide the text to be sent. 

You would need to add another call or another icon that would send all the text all the time.

**Comment by Heziode** [comment]
> Would it be possible to add a toggle setting, disabled by default, which when enabled will send the whole block of text to Antidote instead of only the text from cursor onward (with the exception of selected text functionality which remains the same)?

Yes, it will be possible, I will add this feature as soon as I have a moment.

Thank you @alaroucheDruide for the clarification.

**Comment by Heziode** [comment]
This new feature has been added into [2.1.0](https://github.com/Heziode/obsidian-antidote/releases/tag/2.1.0).
