### ISSUE TITLE
Plugin settings missing

### ISSUE THREAD

**Issue by AdrianSimionov** [Heziode/obsidian-antidote#7]
Plugin settings seems to have gone completely.

Unfortunately this becomes a serious issue for me, as this plugin has 4 icons and is using 3cm+ of screen space.

As an user, I want the option to disable individual icons from being displayed, and have the option to set shortcuts where applicable.

**Comment by Heziode** [comment]
Have you tried to disable and re-enable the plugin?

**Comment by AdrianSimionov** [comment]
That worked. Is there a specific reason for this behavior?

**Comment by Heziode** [comment]
Nope, I have to investigate why.

Probably a problem where the plugin starts without waiting for settings ready. I will look at it this week.
