### ISSUE TITLE
Antidote (Connectix) open API does not support Markdown formatting

### ISSUE THREAD

**Issue by Heziode** [Heziode/obsidian-antidote#9]
- **I'm submitting a ...**
  [X] bug report

- **Summary**

Before using the open API of Connectix, this project uses the old private API. The private API supported markdown formatting into Antidote.

Currently, with the open API, it seems not working.

Does the open API support it? If yes, how can we support it?

Ping @Acibi @alaroucheDruide

Here is a diff:

## With (old) private API
![With (old) private API](https://user-images.githubusercontent.com/16735076/215291365-09f06d0f-7b66-402c-9704-41973767fcb4.png)

## With open API
![With open API](https://user-images.githubusercontent.com/16735076/215291241-4a016b9c-e3fd-4153-829a-1d96e45d02a4.png)

**Comment by alaroucheDruide** [comment]
You should be able to set the filter to markdown when initializing the communication.

@Acibi  should be showing how through a PR. Coming right up!

**Comment by Heziode** [comment]
@alaroucheDruide the problem is still here, even with your patch and the latest version of Antidote / Connectix version 11.3.1.1 (1103.48.87).

**Comment by alaroucheDruide** [comment]
Latest version should be 3.2; try to get the update from Connectix Agent's menu.

**Comment by Heziode** [comment]
Ok, after upgrading Connectix to 3.2 it works.
